package smtp

import (
	"context"
	"fmt"
	"math"
	"math/rand"
	"net/smtp"
	apperrors "rv/internal/errors"
	"rv/pkg/applogger"
	"strconv"
	"time"
)

type Config struct {
	OwnerEmail    string
	OwnerPassword string
	Address       string
	CodeLenght    int
	CodeExp       time.Duration
	MinTTL        time.Duration
}

func NewConfig(ownerEmail, ownerPassword, addres string, codeLenght int, codeExp, minTTL time.Duration) *Config {
	return &Config{
		OwnerEmail: ownerEmail, OwnerPassword: ownerPassword, Address: addres,
		CodeLenght: codeLenght, CodeExp: codeExp, MinTTL: minTTL,
	}
}

type cacheRepo interface {
	GetConfirmCode(ctx context.Context, email string) (string, time.Duration, bool, error)
	SaveConfirmCode(ctx context.Context, email, code string, ttl *time.Duration) error
}

type Service struct {
	logger applogger.Logger

	cacheRepo cacheRepo
	cfg       *Config
}

func NewService(lgr applogger.Logger, cfg *Config, cacheRepo cacheRepo) *Service {
	return &Service{
		logger:    lgr,
		cfg:       cfg,
		cacheRepo: cacheRepo,
	}
}

func (srv *Service) SendConfirmEmailMessage(email, code string) error {
	baseText := `
Hello!
Please, confirm your email with this code: %s. 
If you don't ask this code just ignore this message. 
This message is autogenerated. Please don't answer.
	`
	text := fmt.Sprintf(baseText, code)
	subject := fmt.Sprintf("Email confirm code %s", code)
	return srv.SendMessage(email, text, subject)
}

func (srv *Service) SendMessage(email, messageText, title string) error {
	toEmail := email
	fromEmail := srv.cfg.OwnerEmail

	subject_body := fmt.Sprintf("Subject:%s\n\n %s", title, messageText)
	status := smtp.SendMail(
		srv.cfg.Address,
		smtp.PlainAuth("", fromEmail, srv.cfg.OwnerPassword, "smtp.gmail.com"),
		fromEmail,
		[]string{toEmail},
		[]byte(subject_body),
	)

	return status
}

func (srv *Service) GenerateConfirmCode() string {
	code := rand.Intn(int(math.Pow10(srv.cfg.CodeLenght)))
	return strconv.Itoa(code)
}

func (srv *Service) SendConfirmEmailCode(ctx context.Context, email string) error {
	_, ttl, ex, err := srv.cacheRepo.GetConfirmCode(ctx, email)

	if ex || (err == nil && srv.cfg.MinTTL < ttl) {
		return apperrors.ConfirmCodeAlreadySend
	}

	code := srv.GenerateConfirmCode()
	err = srv.cacheRepo.SaveConfirmCode(ctx, email, code, &srv.cfg.CodeExp)
	go func() {
		err = srv.SendConfirmEmailMessage(email, code)
		if err != nil {
			srv.logger.Warnf("error while sending confirm email message: %s", err.Error())
		}
	}()

	return err
}

func (srv *Service) ConfirmCode(ctx context.Context, email string, code string) error {
	targetCode, _, ex, err := srv.cacheRepo.GetConfirmCode(ctx, email)
	if err != nil {
		return err
	}
	if !ex {
		return apperrors.ConfirmCodeNotExist
	}
	if code != targetCode {
		return apperrors.ConfirmCodeIncorrect
	}
	return nil
}
