// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/rl/api/v1/auth/code": {
            "post": {
                "description": "register new user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "send_confirm_code",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_dto_request.LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.SendCodeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: incorrect_password",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found, confirm_code_already_send",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/auth/confirm": {
            "post": {
                "description": "Подтверждение кода для подтверждения почты, либо сброса пароля. Если сброс пароля, то newPassword обязательное поле.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "confirm_code",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_dto_request.ConfimationCodeRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found, confirm_code_incorrect, confirm_code_not_exist, no_new_password",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/auth/forgot": {
            "post": {
                "description": "Сброс пароля",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "forgot_password",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_dto_request.LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.SendCodeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found, confirm_code_already_send",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/auth/login": {
            "post": {
                "description": "Получение access,refresh токенов по почте и паролю",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_dto_request.LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_services_token.UserTokens"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "possible codes: incorrect_password",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found ",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/auth/refresh": {
            "post": {
                "description": "Получение access,refresh токенов по access, refresh токенам",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "refresh_tokens",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_services_token.UserTokens"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_services_token.UserTokens"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: bad_refresh_token, bad_access_token, bad_token_claims, token_dont_exist, tokens_dont_match",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/auth/register": {
            "post": {
                "description": "register new user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "register_user",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_dto_request.RegisterCredentials"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: not_unique",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/movies/short/{id}": {
            "get": {
                "description": "получить полную информацию о фильме",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movies"
                ],
                "summary": "get_movie_full",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.GetMovieFullResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_path, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/movies/short/{page}": {
            "get": {
                "description": "получить короткие записи о фильмах",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movies"
                ],
                "summary": "get_movies_short",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.GetMoviesShortResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_path, invalid_X-Request-Id, zero_page",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/reviews/movie/{page}": {
            "get": {
                "description": "Получить рецензии фильма",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "get_movie_reviews",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "movie_id",
                        "name": "movie_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.ReviewListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_path, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/reviews/my": {
            "put": {
                "description": "Отредактировать рецензию",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "edit_review",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_dto_request.EditReviewRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id, invalid_authorization_header",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: not_unique, not_my_review",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удалить рецензию",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "delete_review",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_dto_request.DeleteReviewRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id, invalid_authorization_header",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: not_unique, not_my_review",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/reviews/my/new": {
            "post": {
                "description": "Добавить новую рецензию",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "new_review",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_dto_request.NewReviewRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.NewReviewResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id, invalid_authorization_header",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: not_unique",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/reviews/user/{page}": {
            "get": {
                "description": "Получить рецензии, оставленные пользователем",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "get_user_reviews",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.ReviewListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_path, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: not_unique, not_my_review",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/user/picture": {
            "post": {
                "description": "сменить аватарку пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "change_profile_picture",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rv_internal_domain_dto_request.ChangeProfilePicture"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.ChangePictureResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/rl/api/v1/user/profile/{id}": {
            "post": {
                "description": "получить юзера по айди",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get_user_by_id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rv_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rv_internal_domain_dto_response.ChangePictureResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_path, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found",
                        "schema": {
                            "$ref": "#/definitions/rv_pkg_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "multipart.FileHeader": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "header": {
                    "$ref": "#/definitions/textproto.MIMEHeader"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "rv_internal_domain_dto_movies.MoviesFull": {
            "type": "object",
            "properties": {
                "avgRating": {
                    "type": "number"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "imgUrl": {
                    "type": "string"
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rv_internal_domain_dto_reviews.Review"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_movies.MoviesShort": {
            "type": "object",
            "properties": {
                "avgRating": {
                    "type": "number"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "imgUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_request.ChangeProfilePicture": {
            "type": "object",
            "required": [
                "file"
            ],
            "properties": {
                "file": {
                    "$ref": "#/definitions/multipart.FileHeader"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_request.ConfimationCodeRequest": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_request.DeleteReviewRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_request.EditReviewRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                }
            }
        },
        "rv_internal_domain_dto_request.LoginRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_request.NewReviewRequest": {
            "type": "object",
            "required": [
                "review"
            ],
            "properties": {
                "review": {
                    "$ref": "#/definitions/rv_internal_domain_dto_reviews.Review"
                }
            }
        },
        "rv_internal_domain_dto_request.RegisterCredentials": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_response.ChangePictureResponse": {
            "type": "object",
            "properties": {
                "newImgUrl": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_response.GetMovieFullResponse": {
            "type": "object",
            "properties": {
                "movie": {
                    "$ref": "#/definitions/rv_internal_domain_dto_movies.MoviesFull"
                }
            }
        },
        "rv_internal_domain_dto_response.GetMoviesShortResponse": {
            "type": "object",
            "properties": {
                "movies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rv_internal_domain_dto_movies.MoviesShort"
                    }
                }
            }
        },
        "rv_internal_domain_dto_response.NewReviewResponse": {
            "type": "object",
            "properties": {
                "reviewId": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_response.RegisterResponse": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_dto_response.ReviewListResponse": {
            "type": "object",
            "properties": {
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rv_internal_domain_dto_reviews.Review"
                    }
                }
            }
        },
        "rv_internal_domain_dto_response.SendCodeResponse": {
            "type": "object",
            "properties": {
                "nextCodeDelay": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "rv_internal_domain_dto_reviews.Review": {
            "type": "object",
            "required": [
                "description",
                "movieId",
                "rating"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "movieId": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "rv_internal_domain_services_token.UserTokens": {
            "type": "object",
            "required": [
                "accessToken",
                "refreshToken"
            ],
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "rv_pkg_response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/rv_pkg_response.meta"
                },
                "pagination": {
                    "$ref": "#/definitions/rv_pkg_response.pagination"
                }
            }
        },
        "rv_pkg_response.meta": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                }
            }
        },
        "rv_pkg_response.pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                }
            }
        },
        "textproto.MIMEHeader": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "REEL VIEWS API",
	Description:      "This is reel views api service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
